# -*- coding: utf-8 -*-

[global]
persist = true
lxc-mtu = 8192

[frr]
auto_restart = "restart"  # "restart", "reload"(experimental), "-"(no operation)

[cli]
lxcinit   = "lxcinit.sh"
lxd       = "cfglxd"
vty       = "cfgvtyc"
gobgp     = "cfgbgpc"
sys       = "cfgsysc"
